# Generated by Django 2.1 on 2019-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='show_image',
            field=models.BooleanField(default=True),
        ),
    ]
