# Generated by Django 2.1 on 2019-09-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20190924_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video_url',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
