# Generated by Django 2.2.3 on 2019-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_auto_20190926_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='video_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
