# Generated by Django 2.2.3 on 2019-10-10 11:49

from django.db import migrations
import datetime


def add_user(apps, schema_editor):
    User = apps.get_model('user', 'User')
    User.objects.create(login="userAd",
                        password="1111",
                        token="asdadwd2d3ad",
                        token_creation_date=str(datetime.datetime.now()))


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_something'),
    ]

    operations = [
        migrations.RunPython(add_user),
    ]
